Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
       vb.memory = "4096"
       vb.cpus = 2
     end
  config.vm.synced_folder "/home/tparker/Projects/danforth/topp/viper-clone/shared/", "/home/vagrant/shared"
end
